- name: download file
  ansible.builtin.get_url:
    url: https://github.com/jusan-singularity/track-devops-systemd-api/releases/download/v0.1/api
    dest: /tmp
    mode: '0755'
- copy: # <----------- вызываем модуль copy
    src: api.service
    dest: /etc/systemd/system
- name: start api
  command: sh -c "systemctl start api"