- name: Убедиться, что пакет nginx установлен
  apt:
    name: nginx
    state: present
- name: Ansible delete file example
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
- template:
    src: server.conf.j2
    dest: /etc/nginx/conf.d/{{ item.server_name }}.conf
    mode: 0777
  vars:
    server_port: "{{ item.server_port }}"
    server_name: "{{ item.server_name }}"
    server_apps_1: "{{ item.apps_1 }}"
    server_apps_2: "{{ item.apps_2 }}"
  loop:
    - server_port: 80
      server_name: jusan-apps1.kz
      apps_1: local-vps-23:7070
      apps_2: local-vps-24:8080
  notify: reload nginx # <------ вызываем handler с таким названием